# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FeedrApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


pod "DDSpiderChart"
  # Pods for FeedrApp

  target 'FeedrAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FeedrAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
